homepage:
    path:     /
    defaults: { _controller: InleadEasyscreenSearchBundle:Default:index }

search:
    path:     /search
    defaults: { _controller: InleadEasyscreenSearchBundle:Search:search }

departments:
    path:     /departments
    defaults: { _controller: InleadEasyscreenSearchBundle:Search:departments }

branches:
    path:     /branches
    defaults: { _controller: InleadEasyscreenSearchBundle:Provider:branches }

availability:
    path:     /availability
    defaults: { _controller: InleadEasyscreenSearchBundle:Provider:availability }
