inlead_easyscreen_search_homepage:
    path:     /hello/{name}
    defaults: { _controller: InleadEasyscreenSearchBundle:Default:index }

search:
    path:     /search
    defaults: { _controller: InleadEasyscreenSearchBundle:Search:search }

single:
    path:     /single
    defaults: { _controller: InleadEasyscreenSearchBundle:Search:single }
